--liquibase formatted sql

--changeset tinder4dogs:005-create-dog-decision
--comment: one latest decision per directed dog pair
CREATE TABLE dog_decision (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    actor_dog_id  BIGINT      NOT NULL,
    target_dog_id BIGINT      NOT NULL,
    decision      VARCHAR(10) NOT NULL,
    CONSTRAINT pk_dog_decision PRIMARY KEY (id),
    CONSTRAINT fk_dog_decision_actor FOREIGN KEY (actor_dog_id)
        REFERENCES dog (id) ON DELETE CASCADE,
    CONSTRAINT fk_dog_decision_target FOREIGN KEY (target_dog_id)
        REFERENCES dog (id) ON DELETE CASCADE,
    CONSTRAINT uk_dog_decision_actor_target UNIQUE (actor_dog_id, target_dog_id)
);
--rollback DROP TABLE dog_decision;

--changeset tinder4dogs:006-create-dog-match
--comment: one durable match per unordered dog pair
CREATE TABLE dog_match (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    low_dog_id  BIGINT      NOT NULL,
    high_dog_id BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_dog_match PRIMARY KEY (id),
    CONSTRAINT fk_dog_match_low FOREIGN KEY (low_dog_id)
        REFERENCES dog (id) ON DELETE CASCADE,
    CONSTRAINT fk_dog_match_high FOREIGN KEY (high_dog_id)
        REFERENCES dog (id) ON DELETE CASCADE,
    CONSTRAINT ck_dog_match_order CHECK (low_dog_id < high_dog_id),
    CONSTRAINT uk_dog_match_pair UNIQUE (low_dog_id, high_dog_id)
);

CREATE INDEX ix_dog_match_low_created_at ON dog_match (low_dog_id, created_at DESC);
CREATE INDEX ix_dog_match_high_created_at ON dog_match (high_dog_id, created_at DESC);
--rollback DROP INDEX ix_dog_match_high_created_at;
--rollback DROP INDEX ix_dog_match_low_created_at;
--rollback DROP TABLE dog_match;
